#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 18, 2021 04:53:27 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import test3_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Top (root)
    test3_support.init(root, top)
    root.mainloop()

w = None
def create_Top(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Top(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Top (w)
    test3_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Top():
    global w
    w.destroy()
    w = None

class Top:
    def ex1(self):
        if self.ex1_input == "":
            self.ex1_ans.configure(text="please insert a string")
            return
        string = self.ex1_input.get()
        max_word = ""
        max_len = 0
        #cwd = os.getcwd()
        #cwd += "dict.txt"
        #print(cwd)
        with open("c:\\Users\\Gvili\\Desktop\\quiz3\\dict.txt", "r") as dict_file:
            for word in dict_file:
                clean_word = word.strip('\n')
                if clean_word in string:
                    if max_len < len(clean_word):
                        max_word = clean_word
                        max_len = len(clean_word)
        #print("The longest word in the string is", max_word, "and her length is", max_len)
        string = "Answer: The longest word in the string is" + max_word + "and her length is" + str(max_len)
        self.ex1_ans.configure(text= string)
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x419+771+383")
        top.minsize(120, 1)
        top.maxsize(2198, 1215)
        top.resizable(1,  1)
        top.title("im here")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.ex1_btn = ttk.Button(top)
        self.ex1_btn.place(relx=0.783, rely=0.155, height=25, width=76)
        self.ex1_btn.configure(takefocus="")
        self.ex1_btn.configure(text='''Calculate''')
        self.ex1_btn.configure(command = self.ex1)

        self.msg = tk.Message(top)
        self.msg.place(relx=0.017, rely=-0.021, relheight=0.208, relwidth=0.433)
        self.msg.configure(background="#d9d9d9")
        self.msg.configure(foreground="#000000")
        self.msg.configure(highlightbackground="#d9d9d9")
        self.msg.configure(highlightcolor="black")
        self.msg.configure(text='''Welcome, this software will help you solve
quiz 3 quickly without coding, just paste the
data and press "Calculate"''')
        self.msg.configure(width=260)

        self.ex1_input = ttk.Entry(top)
        self.ex1_input.place(relx=0.183, rely=0.155, relheight=0.05
                , relwidth=0.543)
        self.ex1_input.configure(takefocus="")
        self.ex1_input.configure(cursor="ibeam")

        self.Message1 = tk.Message(top)
        self.Message1.place(relx=0.017, rely=0.153, relheight=0.053
                , relwidth=0.167)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Question 1: S =''')
        self.Message1.configure(width=100)

        self.ex1_ans = tk.Message(top)
        self.ex1_ans.place(relx=0.1, rely=0.222, relheight=0.05, relwidth=0.1)
        self.ex1_ans.configure(background="#d9d9d9")
        self.ex1_ans.configure(foreground="#000000")
        self.ex1_ans.configure(highlightbackground="#d9d9d9")
        self.ex1_ans.configure(highlightcolor="black")
        self.ex1_ans.configure(text='''Answer :''')
        self.ex1_ans.configure(width=60)

        self.Message2 = tk.Message(top)
        self.Message2.place(relx=0.028, rely=0.303, relheight=0.053
                , relwidth=0.133)
        self.Message2.configure(background="#d9d9d9")
        self.Message2.configure(cursor="fleur")
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(text='''Question 2: S =''')
        self.Message2.configure(width=80)

        self.ex2_input = ttk.Entry(top)
        self.ex2_input.place(relx=0.183, rely=0.31, relheight=0.05
                , relwidth=0.543)
        self.ex2_input.configure(takefocus="")
        self.ex2_input.configure(cursor="ibeam")

        self.ex2_btn = ttk.Button(top)
        self.ex2_btn.place(relx=0.783, rely=0.31, height=25, width=76)
        self.ex2_btn.configure(takefocus="")
        self.ex2_btn.configure(text='''Calculate''')

        self.ex2_ans = tk.Message(top)
        self.ex2_ans.place(relx=0.1, rely=0.377, relheight=0.053, relwidth=0.1)
        self.ex2_ans.configure(background="#d9d9d9")
        self.ex2_ans.configure(foreground="#000000")
        self.ex2_ans.configure(highlightbackground="#d9d9d9")
        self.ex2_ans.configure(highlightcolor="black")
        self.ex2_ans.configure(text='''Answer :''')
        self.ex2_ans.configure(width=60)

        self.Message3 = tk.Message(top)
        self.Message3.place(relx=0.017, rely=0.444, relheight=0.05
                , relwidth=0.167)
        self.Message3.configure(background="#d9d9d9")
        self.Message3.configure(foreground="#000000")
        self.Message3.configure(highlightbackground="#d9d9d9")
        self.Message3.configure(highlightcolor="black")
        self.Message3.configure(text='''Question 3: A1={''')
        self.Message3.configure(width=100)

        self.ex3_a1_input = ttk.Entry(top)
        self.ex3_a1_input.place(relx=0.183, rely=0.444, relheight=0.05
                , relwidth=0.56)
        self.ex3_a1_input.configure(takefocus="")
        self.ex3_a1_input.configure(cursor="ibeam")

        self.Message4 = tk.Message(top)
        self.Message4.place(relx=0.75, rely=0.444, relheight=0.05
                , relwidth=0.033)
        self.Message4.configure(background="#d9d9d9")
        self.Message4.configure(foreground="#000000")
        self.Message4.configure(highlightbackground="#d9d9d9")
        self.Message4.configure(highlightcolor="black")
        self.Message4.configure(text='''}''')
        self.Message4.configure(width=20)

        self.Message3_1 = tk.Message(top)
        self.Message3_1.place(relx=0.117, rely=0.511, relheight=0.05
                , relwidth=0.067)
        self.Message3_1.configure(background="#d9d9d9")
        self.Message3_1.configure(foreground="#000000")
        self.Message3_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1.configure(highlightcolor="black")
        self.Message3_1.configure(text='''A2={''')
        self.Message3_1.configure(width=40)

        self.ex3_a2_input = ttk.Entry(top)
        self.ex3_a2_input.place(relx=0.183, rely=0.511, relheight=0.048
                , relwidth=0.56)
        self.ex3_a2_input.configure(takefocus="")
        self.ex3_a2_input.configure(cursor="fleur")

        self.Message4_1 = tk.Message(top)
        self.Message4_1.place(relx=0.75, rely=0.511, relheight=0.05
                , relwidth=0.033)
        self.Message4_1.configure(background="#d9d9d9")
        self.Message4_1.configure(cursor="fleur")
        self.Message4_1.configure(foreground="#000000")
        self.Message4_1.configure(highlightbackground="#d9d9d9")
        self.Message4_1.configure(highlightcolor="black")
        self.Message4_1.configure(text='''}''')
        self.Message4_1.configure(width=20)

        self.Message3_1_1 = tk.Message(top)
        self.Message3_1_1.place(relx=0.117, rely=0.578, relheight=0.053
                , relwidth=0.067)
        self.Message3_1_1.configure(background="#d9d9d9")
        self.Message3_1_1.configure(foreground="#000000")
        self.Message3_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1.configure(highlightcolor="black")
        self.Message3_1_1.configure(text='''A3={''')
        self.Message3_1_1.configure(width=40)

        self.ex3_a3_input = ttk.Entry(top)
        self.ex3_a3_input.place(relx=0.183, rely=0.578, relheight=0.048
                , relwidth=0.56)
        self.ex3_a3_input.configure(takefocus="")
        self.ex3_a3_input.configure(cursor="fleur")

        self.Message4_1_1 = tk.Message(top)
        self.Message4_1_1.place(relx=0.75, rely=0.578, relheight=0.053
                , relwidth=0.033)
        self.Message4_1_1.configure(background="#d9d9d9")
        self.Message4_1_1.configure(foreground="#000000")
        self.Message4_1_1.configure(highlightbackground="#d9d9d9")
        self.Message4_1_1.configure(highlightcolor="black")
        self.Message4_1_1.configure(text='''}''')
        self.Message4_1_1.configure(width=20)

        self.Message2_1 = tk.Message(top)
        self.Message2_1.place(relx=0.022, rely=0.706, relheight=0.053
                , relwidth=0.15)
        self.Message2_1.configure(background="#d9d9d9")
        self.Message2_1.configure(foreground="#000000")
        self.Message2_1.configure(highlightbackground="#d9d9d9")
        self.Message2_1.configure(highlightcolor="black")
        self.Message2_1.configure(text='''Question 4: L = {''')
        self.Message2_1.configure(width=90)

        self.ex3_ans = tk.Message(top)
        self.ex3_ans.place(relx=0.1, rely=0.644, relheight=0.05, relwidth=0.1)
        self.ex3_ans.configure(background="#d9d9d9")
        self.ex3_ans.configure(foreground="#000000")
        self.ex3_ans.configure(highlightbackground="#d9d9d9")
        self.ex3_ans.configure(highlightcolor="black")
        self.ex3_ans.configure(text='''Answer :''')
        self.ex3_ans.configure(width=60)

        self.Message4_2 = tk.Message(top)
        self.Message4_2.place(relx=0.75, rely=0.704, relheight=0.05
                , relwidth=0.033)
        self.Message4_2.configure(background="#d9d9d9")
        self.Message4_2.configure(cursor="fleur")
        self.Message4_2.configure(foreground="#000000")
        self.Message4_2.configure(highlightbackground="#d9d9d9")
        self.Message4_2.configure(highlightcolor="black")
        self.Message4_2.configure(text='''}''')
        self.Message4_2.configure(width=20)

        self.ex3_a3_input_1 = ttk.Entry(top)
        self.ex3_a3_input_1.place(relx=0.183, rely=0.711, relheight=0.048
                , relwidth=0.56)
        self.ex3_a3_input_1.configure(takefocus="")
        self.ex3_a3_input_1.configure(cursor="fleur")

        self.ex3_btn = ttk.Button(top)
        self.ex3_btn.place(relx=0.783, rely=0.511, height=25, width=76)
        self.ex3_btn.configure(takefocus="")
        self.ex3_btn.configure(text='''Calculate''')

        self.ex4_btn = ttk.Button(top)
        self.ex4_btn.place(relx=0.783, rely=0.702, height=25, width=76)
        self.ex4_btn.configure(takefocus="")
        self.ex4_btn.configure(text='''Calculate''')

        self.Message5 = tk.Message(top)
        self.Message5.place(relx=0.383, rely=0.907, relheight=0.05
                , relwidth=0.15)
        self.Message5.configure(background="#d9d9d9")
        self.Message5.configure(cursor="fleur")
        self.Message5.configure(foreground="#000000")
        self.Message5.configure(highlightbackground="#d9d9d9")
        self.Message5.configure(highlightcolor="black")
        self.Message5.configure(text='''© - Dudu Gvili''')
        self.Message5.configure(width=90)

        self.ex4_ans = tk.Message(top)
        self.ex4_ans.place(relx=0.1, rely=0.778, relheight=0.05, relwidth=0.1)
        self.ex4_ans.configure(background="#d9d9d9")
        self.ex4_ans.configure(foreground="#000000")
        self.ex4_ans.configure(highlightbackground="#d9d9d9")
        self.ex4_ans.configure(highlightcolor="black")
        self.ex4_ans.configure(text='''Answer :''')
        self.ex4_ans.configure(width=60)

if __name__ == '__main__':
    vp_start_gui()





